# Generated by Django 5.1.1 on 2024-09-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='senha',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='medicodentista',
            name='senha',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='senha',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
