# Generated by Django 5.1.1 on 2024-09-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0003_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
