# Generated by Django 5.1.1 on 2024-10-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0003_alter_paciente_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='periodo_trabalho',
            field=models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('ambos', 'Ambos')], default='ambos', max_length=10),
        ),
    ]
