# Generated by Django 5.1.1 on 2024-10-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0004_dentista_periodo_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentista',
            name='periodo_trabalho',
            field=models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('diurno', 'Diurno')], default='diurno', max_length=10),
        ),
    ]
