# Generated by Django 5.1.1 on 2024-09-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0005_rename_medicodentista_consulta_medico_dentista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
