# Generated by Django 5.1.1 on 2024-10-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0006_dentista_cro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentista',
            name='cro',
            field=models.CharField(max_length=20),
        ),
    ]
