# Generated by Django 5.1.1 on 2024-09-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0006_alter_paciente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicodentista',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='senha',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='medicodentista',
            name='senha',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='recepcionista',
            name='senha',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
