# Generated by Django 5.1.1 on 2024-10-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0007_alter_dentista_cro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentista',
            name='cro',
        ),
    ]
