# Generated by Django 5.1.1 on 2024-10-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0008_remove_dentista_cro'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='cro',
            field=models.CharField(default='Masculino', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], default='Masculino', max_length=15),
            preserve_default=False,
        ),
    ]
