# Generated by Django 5.1.1 on 2024-10-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0009_dentista_cro_funcionario_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.DateTimeField(verbose_name='Serviço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
