# Generated by Django 5.1.1 on 2024-10-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0011_alter_servico_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_hora',
            field=models.DateTimeField(unique=True, verbose_name='Data e Hora'),
        ),
    ]
