# Generated by Django 5.1.1 on 2024-10-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0012_alter_consulta_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_hora',
            field=models.DateTimeField(verbose_name='Data e Hora'),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='cro',
            field=models.CharField(max_length=20, unique=True, verbose_name='CRO'),
        ),
    ]
