# Generated by Django 5.1.1 on 2024-10-15 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0014_alter_consulta_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaMedica.servico'),
            preserve_default=False,
        ),
    ]
